### ISSUE TITLE
can not run the demo

### ISSUE THREAD

**Issue by chenpingbupt** [ooflorent/graphql-parser#3]
```
ThisMbp:~ ziang$ node demo.js 
/Users/ziang/demo.js:1
(function (exports, require, module, __filename, __dirname) { import graphql f
                                                              ^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

=================env as below================
ThisMbp:~ ziang$ uname -a
Darwin ThisMbp.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
ThisMbp:~ ziang$ node -v
v0.12.2
ThisMbp:~ ziang$ npm -v
2.7.6
ThisMbp:~ ziang$ npm install --save graphql-parser
graphql-parser@1.3.0 node_modules/graphql-parser
├── graphql-types@1.1.0
├── lodash@3.9.1
└── parsly@3.0.0 (babel-runtime@5.4.3)

```

```
ThisMbp:~ ziang$ cat demo.js 
```

``` js
import graphql from 'graphql-parser'

const IMAGE_WIDTH = 80
const IMAGE_HEIGHT = 80

const PostFragment = graphql`
  post {
    title,
    published_at
  }
`
const UserQuery = graphql`
  user(<id>) {
    nickname,
    avatar.resize(${IMAGE_WIDTH}, ${IMAGE_HEIGHT}) {
      url
    },
    posts.first(<count>) {
      count,
      edges {
        node {
          ${ PostFragment() }
        }
      }
    }
  }
`

const query = UserQuery({
  id: 1337,
  count: 10,
})
```

**Comment by ooflorent** [comment]
The demo must be transpiled to ES5 or interpreted through babel:

``` js
npm i babel
./node_modules/.bin/babel-node demo.js
```

**Comment by chenpingbupt** [comment]
ok, thanks!
